안녕하세요. 수강생 여러분~! Chapter21 ~ 32 수업은 잘 들으셨나요?

Chapter21 ~ 32의 수업 내용을 바탕으로 아래 문제를 풀어주시면 됩니다.


<br>


[**답변 입력 방법**]

문제 아래에 있는 코드 입력창에 정답코드를 작성하신 후  __▷ 버튼을 클릭해 코드를 실행__ 해보세요<br>

---

[문제 1]
사용자로부터 이름과 나이를 입력 받아, "안녕하세요, [이름]님! 당신은 [나이]살입니다."라고 출력하는 함수 greet_user를 작성하세요.

In [2]:
def greet_user(name, age):
    print(f"안녕하세요, {name}님! 당신은 {age}살입니다.")

name = input("이름을 입력하세요: ")
age = input("나이를 입력하세요: ")

greet_user(name, age)

이름을 입력하세요: 김민주
나이를 입력하세요: 26
안녕하세요, 김민주님! 당신은 26살입니다.

---

[문제 2] 여러 숫자를 입력받아 그 합계를 반환하는 함수 sum_numbers를 작성하세요. 이 때, 가변 매개변수를 사용하세요.

In [6]:
def sum_numbers(*args):
    total = 0
    for num in args:
        total += num
    return total

print("숫자를 입력하세요. (종료하려면 q 입력)")

while True:
    user_input = input("숫자 입력: ")

    if user_input.lower() == "q":   # q 입력하면 종료
        break

        try:
            num = int(user_input)
            numbers.append(num)
        except ValueError:
            print("숫자를 입력하거나 q를 입력해 종료하세요.")

# 합계 계산
result = sum_numbers(*numbers)
print("입력한 숫자들의 합계:", result)

숫자를 입력하세요. (종료하려면 q 입력)
숫자 입력: 2
숫자 입력: 3
숫자 입력: q
입력한 숫자들의 합계: 6

---

[문제 3] 사용자의 이름을 출력하는 함수 print_name을 작성하세요. 만약 이름이 주어지지 않았다면, 기본값으로 "익명"을 사용하세요.

In [10]:
def print_name(name="익명"):
    print(f"안녕하세요, {name}님!")

name = input("이름을 입력하세요: ")

if name:
    print_name(name)
else:
    print_name()

이름을 입력하세요: 김민주
안녕하세요, 김민주님!

---

[문제 4] 사용자의 이름, 나이, 성별을 출력하는 함수 print_info를 작성하세요. 이 때, 모든 매개변수는 키워드 매개변수로만 받도록 하세요.

In [11]:
def print_info(*,name, age, gender):
    print(f"이름: {name}")
    print(f"나이: {age}")
    print(f"성별: {gender}")

name = input("이름을 입력하세요: ")
age = input("나이를 입력하세요: ")
gender = input("성별을 입력하세요: ")

print_info(name=name, age=age, gender=gender)

이름을 입력하세요: 김민주
나이를 입력하세요: 26
성별을 입력하세요: 여
이름: 김민주
나이: 26
성별: 여

---

[문제 5] 두 개의 정수를 받아 합을 반환하는 함수 add를 작성하세요. 매개변수와 반환값에 타입 어노테이션을 추가하세요.

In [14]:
def sum_numbers(*args: int) -> int:
    total: int = 0
    for num in args:
        total += num
    return total

number1 = int(input("첫 번째 숫자: "))
number2 = int(input("두 번째 숫자: "))

result: int = sum_numbers(number1,number2)
print(result)

첫 번째 숫자: 3
두 번째 숫자: 4
7

---

[문제 6] 0부터 시작하여 n까지의 숫자 중에서 홀수만 생성하는 제너레이터 odd_numbers를 작성하세요.

In [15]:
def odd_numbers(n: int):
    for i in range(1, n + 1, 2):  # 1부터 n까지 2씩 증가 → 홀수
        yield i

n = 10

for num in odd_numbers(n):
    print(num)

1
3
5
7
9

---

[문제 7] 두 숫자를 더하는 람다 함수를 작성하고, 이를 변수에 할당한 후 사용하세요.

In [16]:
add = lambda x, y: x + y

result = add(3, 5)
print(result)

8

---

[문제 8] 사용자로부터 3개의 숫자를 입력받아, 이를 튜플로 만든 후 최소값과 최대값을 출력하는 함수 min_max를 작성하세요.

In [19]:
def min_max() -> None:
    numbers: Tuple[int, int, int] = tuple(
        int(input(f"{i+1}번째 숫자 입력: ")) for i in range(3)
    )

    minimum: int = min(numbers)
    maximum: int = max(numbers)

    print(f"입력한 숫자: {numbers}")
    print(f"최소값: {minimum}")
    print(f"최대값: {maximum}")

min_max()

1번째 숫자 입력: 10
2번째 숫자 입력: 2
3번째 숫자 입력: 8
입력한 숫자: (10, 2, 8)
최소값: 2
최대값: 10

---

[문제 9] 주어진 숫자가 짝수인지 확인하는 함수 is_even을 작성하세요. 짝수라면 True를, 아니라면 False를 반환하세요. 함수 내에서 조기 리턴을 활용하세요.

In [21]:
def is_even(number: int) -> bool:
    if number % 2 == 0:
        return True
    else:
        return False

number = int(input("숫자 입력: "))
result = is_even(number)
print(result)

숫자 입력: 30
True

---

[문제 10] 팩토리얼을 계산하는 재귀 함수 factorial을 작성하세요.

In [22]:
def factorial(n: int) -> int:
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

print(factorial(5))

120

---

[문제 11] 문자열 리스트를 받아, 각 문자열의 길이를 출력하는 함수 print_lengths를 작성하세요.

In [28]:
def print_lengths(strings):
    [print(f"'{s}'의 길이: {len(s)}") for s in strings]

fruits = ["apple", "banana", "kiwi"]
print_lengths(fruits)

'apple'의 길이: 5
'banana'의 길이: 6
'kiwi'의 길이: 4

---

[문제 12] 두 문자열을 받아서 긴 문자열을 반환하는 함수 longer_string을 작성하세요. 만약 두 문자열의 길이가 같다면, 첫 번째 문자열을 반환하세요.

In [29]:
def longer_string(s1: str, s2: str) -> str:
    if len(s1) >= len(s2):
        return s1
    else:
        return s2

s1 = input("첫 번째 문자열: ")
s2 = input("두 번째 문자열: ")

result = longer_string(s1, s2)
print(f"긴 문자열: {result}")

첫 번째 문자열: 가나
두 번째 문자열: 다라
긴 문자열: 가나